# A consolidated and standardized version of your Netlify config

[build]
  command = ""
  publish = "."
  # The functions directory is now declared here, which is the most standard practice.
  functions = "netlify/functions"

[functions]
  # Global settings for all functions, like your bundler choice, go here.
  node_bundler = "esbuild"

# Your scheduled function settings remain unchanged.
[functions.syncDealsFinal]
  schedule = "@hourly"
