# This file configures the build and deployment settings for Netlify.

[build]
  # The command to build the site. Empty because it's functions-only.
  command = ""
  # The directory to publish. "." means the root directory.
  publish = "."
  # The directory where Netlify will find the serverless functions.
  functions = "netlify/functions"

[functions]
  # Specifies the bundler to use for Node.js functions.
  node_bundler = "esbuild"

# Schedules the syncDealsFinal function to run every minute.
[functions.syncDealsFinal]
  schedule = "* * * * *"

# FOR TESTING: Schedules the main call sync to run every minute.
# NOTE: Change back to "4-59/5 * * * *" for production.
[functions."synccalllogs-background"]
  schedule = "* * * * *"

# FOR TESTING: Schedules the leaderboard summary function to run every minute.
# NOTE: Change back to "*/5 * * * *" for production.
[functions."syncLeaderboardStats"]
  schedule = "* * * * *"
