# This file configures the build and deployment settings for Netlify.

[build]
  # The command to build the site. Empty because it's functions-only.
  command = ""
  # The directory to publish. "." means the root directory.
  publish = "."
  # The directory where Netlify will find the serverless functions.
  functions = "netlify/functions"

[functions]
  # Specifies the bundler to use for Node.js functions.
  node_bundler = "esbuild"

# Schedules the syncDealsFinal function to run once an hour.
[functions.syncDealsFinal]
  schedule = "@hourly"

# The schedule for the main call sync remains.
[functions."synccalllogs-background"]
  schedule = "4-59/5 * * * *"

# The schedule for syncLeaderboardStats has been temporarily removed for testing.
# The function will now only be a standard, on-demand function.
# [functions."syncLeaderboardStats"]
#  schedule = "*/5 11-21 * * *"
